from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import tempfile
import json
import os


router = APIRouter(prefix="/export", tags=["Export"])


@router.post("/shop-drawing")
async def export_shop_drawing(data: dict):
    """
    Export shop drawing checker result to a formatted PDF (Procore style).
    """

    try:
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
        pdf_path = tmp.name

        c = canvas.Canvas(pdf_path, pagesize=letter)
        width, height = letter

        x = 40
        y = height - 50

        # -------- HEADER --------
        c.setFont("Helvetica-Bold", 18)
        c.drawString(x, y, "Shop Drawing Analysis Report")
        y -= 30

        c.setFont("Helvetica", 11)
        c.drawString(x, y, "Generated by Construct AI")
        y -= 25

        # -------- SECTIONS --------
        def section(title):
            nonlocal y
            c.setFont("Helvetica-Bold", 13)
            c.drawString(x, y, title)
            y -= 20

        def write_text(text):
            nonlocal y
            c.setFont("Helvetica", 10)
            for line in text.split("\n"):
                c.drawString(x, y, line)
                y -= 12
                if y < 60:
                    c.showPage()
                    y = height - 50

        # MAIN TITLE / SUMMARY
        section("Summary")
        write_text(data.get("summary", "No summary"))

        # ISSUES
        if "critical_issues" in data:
            section("Critical Issues")
            write_text("\n".join(data["critical_issues"]) or "None")

        if "dimension_conflicts" in data:
            section("Dimension Conflicts")
            write_text("\n".join(data["dimension_conflicts"]) or "None")

        if "missing_information" in data:
            section("Missing Information")
            write_text("\n".join(data["missing_information"]) or "None")

        if "code_violations" in data:
            section("Code Violations")
            write_text("\n".join(data["code_violations"]) or "None")

        if "detailing_errors" in data:
            section("Detailing Errors")
            write_text("\n".join(data["detailing_errors"]) or "None")

        if "structural_conflicts" in data:
            section("Structural Conflicts")
            write_text("\n".join(data["structural_conflicts"]) or "None")

        # RFIs
        section("Suggested RFIs")

        rfi_list = data.get("rfi_to_generate", [])
        if not rfi_list:
            write_text("No RFIs generated")
        else:
            for rfi in rfi_list:
                write_text(f"• {rfi.get('title', '')}")
                write_text(f"  - Question: {rfi.get('question', '')}")
                write_text(f"  - Reason: {rfi.get('reason', '')}")
                write_text("")

        c.save()

        return FileResponse(
            pdf_path,
            media_type="application/pdf",
            filename="shop_drawing_report.pdf"
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
